#!/bin/sh

PREREQ=""

prereqs () {
	echo "${PREREQ}"
}

case "${1}" in
	prereqs)
		prereqs
		exit 0
		;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /opt/ibm/pef/bin/esmb-get-file
copy_exec /opt/ibm/pef/bin/pef_svm_keyscript

exit 0
